apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: { app: mlops-svc }
  template:
    metadata:
      labels: { app: mlops-svc }
    spec:
      containers:
      - name: svc
        image: dupjunsu/mlops-svc:0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: MODEL_PATH
          value: /app/model.onnx
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet: { path: /health, port: 8000 }
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /health, port: 8000 }
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-svc
  namespace: default
spec:
  selector:
    app: mlops-svc
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
